### PR TITLE
Config File with Python Input Interface

### PR DESCRIPTION
**Pull request by teknicsrx7**
Ok so my config.js from yesterday is back.

I branched off and added config.py. This opens and direct text entry window for the user which will automatically edit the config.js file with their chosen options. This will prevent any issues with having users directly editing files.

Only tested on Windows 10, no issues and I think there's enough checks to prevent improper data entry (such as a making sure they fully write "true" or "false", ensuring numbers are used where needed etc)

### CODE REVIEW

**Comment by FrostTheFox** [comment]
Alrighty, let me test and we can move this in.

My plan is to just throw config.py into our install.bat and install.sh.

**Comment by teknicsrx7** [comment]
sounds good, definitely give it a test, i think i thought up all the possible incorrect answer for the config setup but i may have forgotten some, also i only have windows to test on

**Comment by FrostTheFox** [comment]
don't worry i'll get this done by the end of the night but i'm working on a yt video atm :)

**Comment by teknicsrx7** [comment]
No worries I'm gonna setup my github properly so the "merge" crap goes away on my PRs

**Comment by FrostTheFox** [comment]
ok, YT video rendering, cloning and testing.

**Comment by FrostTheFox** [comment]
Can you make the recommend for use random password true?

And have the static password for accounts one say (only if random password false)? something like that

**Comment by FrostTheFox** [comment]
Alright, so it worked for me, once you make the changes above I can merge it and update documentation accordingly.

**Comment by teknicsrx7** [comment]
alright yea i can get both those to happen, have it up in a bit

**Comment by teknicsrx7** [comment]
ok that wraps that up

**Comment by FrostTheFox** [comment]
Alright, awesome. I'll merge this, update install.bat/.sh and whatnot

**Comment by teknicsrx7** [comment]
great

**Pull request merged**
