### PR TITLE
Random Birfdee v2

### PR DESCRIPTION
**Pull request by jnovack**
The getMonth()+1 was the problem.

Months in Javascript are 0-based. #derp

### CODE REVIEW

**Comment by FrostTheFox** [comment]
fix travis pls k thanks

**Comment by deirdresm** [comment]
First attempt to use, I got a birthdate of 1964-61-8.

Note: I'm on Mac.
screen shot 2016-09-20 at 12 48 46 pm

**Comment by FrostTheFox** [comment]
:P I just started experiencing a failure about local variable 'password' reference before assignment in config.py when I pulled, so I didn't even get to test yet

**Comment by jnovack** [comment]
Sigh.  Do not use until I fix.

**Comment by FrostTheFox** [comment]
:P

**Review by FrostTheFox — APPROVED** [review]
config.py doesn't give that error anymore, it will complain about the country not having an end " (which I fixed on latest, just not in your branch), so that'll be no problem.

**Pull request merged**
