### PR TITLE
Randomize birfdate

### PR DESCRIPTION
**Pull request by jnovack**
Randomize the birthdate between 1952 and 1998 each iteration.

Guaranteed to be 18+.

### CODE REVIEW

**Comment by FrostTheFox** [comment]
Have you checked to see if the birthdate function actually works? Because we've had some reports of it breaking

**Comment by FrostTheFox** [comment]
also rebase pls

**Comment by teknicsrx7** [comment]
Now that I have my git setup properly I'll do the birthday test later today. Think the complaint was birthdate changing causes it to stall after 2-5 accounts created

**Comment by jnovack** [comment]
The birthday failing is when it generate a date less than (13 years ago?)  So I just made the user always over 18.

You dont have to rebase, just add in the code in your next update. I don't care about teh credit. ;)

**Comment by FrostTheFox** [comment]
okie dokie /shrug

I'll include it sometime today, for now I'll just leave it open

**Comment by FrostTheFox** [comment]
Tries to input the time with the DOB as well, doesn't tend to work very well :P

**Comment by FrostTheFox** [comment]
Closing for now.

**Pull request closed without merging**
